---
title: "Client Report - Can You Predict That?"
subtitle: "Course DS 250"
author: "Dallin Moak"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import os

_ = os.getcwd()
```


```{python}
from p4_source import df

df.describe()
```


## Elevator pitch
_A SHORT (2-3 SENTENCES) PARAGRAPH THAT `DESCRIBES KEY INSIGHTS` TAKEN FROM METRICS IN THE PROJECT RESULTS THINK TOP OR MOST IMPORTANT RESULTS._ (Note: this is not a summary of the project, but a summary of the results.)

_A Client has requested this analysis and this is your one shot of what you would say to your boss in a 2 min elevator ride before he takes your report and hands it to the client._

## QUESTION|TASK 1

__Create 2-3 charts that evaluate potential relationships between the home variables and `before1980`.__ Explain what you learn from the charts that could help a machine learning algorithm. 

_I checked for a simple relationship between `before1980` and `livearea` average. the older ones are a little bit smaller on average, but it's not much. Also, I checked the `sprice` average and it seems that the older ones are a little bit cheaper on average. This tells me that a very basic naive bayes model might not be able to find simple single-variable relationships._

```{python}
from p4_source import livearea_chart, sprice_chart

livearea_chart
sprice_chart
```

## QUESTION|TASK 2

__Build a classification model labeling houses as being built “before 1980” or “during or after 1980”.__ Your goal is to reach or exceed 90% accuracy. Explain your final model choice (algorithm, tuning parameters, etc) and describe what other models you tried.  

_Ok the obvious starting point is the GaussianNB model. I'm going to follow standard practice and split out the data set into test and training data, then split things out into features and labels where the label is just values for `before1980` and features contains all the other columns in the dataset, but with no cheating by giving the model the answers (AKA excluding the `before1980` and `yrbuilt` columns). I did some basic reading about the GaussianNB parameters of priors and var_smoothing, and it seems like for priors, leaving a default value and letting the balance of classes be set by the training data instead of forcing some assumption of 50-50 is the best. for the var_smoothing, it seems like there's not any accuracy gained by turning it down lower than the default value. I will increase it if there's any errors so that it doesn't get stuck on similar values._

_here's the GaussianNB model I built:_
```{python}
from p4_source import gaussianNB_score

f"GaussianNB accuracy: {gaussianNB_score}"
```


## QUESTION|TASK 3

__Justify your classification model by discussing the most important features selected by your model.__ This discussion should include a feature importance chart and a description of the features. 

_type your results and analysis here_

```{python}

```


## QUESTION|TASK 4

__Describe the quality of your classification model using 2-3 different evaluation metrics.__ You also need to explain how to interpret each of the evaluation metrics you use.  

_type your results and analysis here_

```{python}

```

---

## STRETCH QUESTION|TASK 1

__Repeat the classification model using 3 different algorithms.__ Display their Feature Importance, and Decision Matrix. Explian the differences between the models and which one you would recommend to the Client.   

_type your results and analysis here_

```{python}


```


## STRETCH QUESTION|TASK 2

__Join the `dwellings_neighborhoods_ml.csv` data to the `dwelling_ml.csv` on the `parcel` column to create a new dataset. Duplicate the code for the stretch question above and update it to use this data.__ Explain the differences and if this changes the model you recomend to the Client.   

_type your results and analysis here_

```{python}


```


## STRETCH QUESTION|TASK 3

__Can you build a model that predicts the year a house was built?__ Explain the model and the evaluation metrics you would use to determine if the model is good.  

_type your results and analysis here_

```{python}


```

---
